trigger: none
  
stages:
  - stage: 'Test'
    jobs:
    - job: RunTests
      pool: "Monai VMSS"
      strategy:
        matrix:
          Python3.6:
            python.version: '3.8'
        maxParallel: 2
      variables:
        - group: monai-stream-vars

      steps:
      # - task: UsePythonVersion@0
      #   inputs:
      #     versionSpec: $(python.version)
      - script: |
          echo "$NGC_KEY" | docker login -u $ARTUSER $(NGC_KEY) --password-stdin
          docker build Dockerfile.base
          