trigger: none
  
stages:
  - stage: 'Test'
    jobs:
    - job: RunTests
      pool: "Monai VMSS"
      strategy:
        maxParallel: 1
      steps:

      - task: DownloadSecureFile@1
        name: appModel
        displayName: 'Download app model'
        inputs:
          secureFile: 'monai_unet_x86.engine'

      - task: DownloadSecureFile@1
        name: appModelConfig
        displayName: 'Download app model config.pbtxt'
        inputs:
          secureFile: 'config_us_trt.pbtxt'


      - task: DownloadSecureFile@1
        name: appVideo
        displayName: 'Download sample video'
        inputs:
          secureFile: 'Q000_04_tu_segmented_ultrasound_256.avi'

      - script: |
          mkdir -p models/monai_unet_trt/1 videos

          echo Installing $(appModel.secureFilePath) to the application model directory...
          sudo cp $(appModel.secureFilePath) models/monai_unet_trt/1/us_unet.engine

          echo Installing $(appModelConfig.secureFilePath) to the application model config directory...
          sudo cp $(appModelConfig.secureFilePath) models/monai_unet_trt/config.pbtxt

          echo Installing $(appModel.secureFilePath) to the application video directory...
          sudo cp $(appModel.secureFilePath) videos/Q000_04_tu_segmented_ultrasound_256.avi

          sudo chown -R $USER models videos
          sudo chgrp -R $USER models videos

      - bash: docker build -f Dockerfile.devel -t monai-stream-test-image .
        displayName: build MONAI stream test image

      - bash: docker run  --rm  --runtime=nvidia monai-test sample/monaistream-us-cupy-app/main.py
        displayName: Test MONAI stream image
