name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-monaistream-cupy-pp-app:
    runs-on: ["agx"]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          # path: "/app"
          clean: true

      - name: Make temp directory for nee files
        run: mkdir tmp

      - name: Make Videos Directory, copy endoscopy video
        run: |
          mkdir videos
          cp /opt/stream/CholecSeg8K/endo.mp4 ./videos/

      # - name: Copy in files
      #   run: | 
      #     mkdir models/monai_unet_trt/1
      #     cp /opt/stream/CholecSeg8K/cholec_unet_864x480_cagx.engine models/monai_unet_trt/1/monai_unet.engine
      #     cp /opt/stream/CholecSeg8K/config_cholec_trt.pbtxt models/monai_unet_trt/config.pbtxt

      # - name: Change path of app
      #     run: |


      - name: Run Test
        run: |
          export DISPLAY=:0.0
          PYTHONPATH=src/ python3 sample/monaistream-cupy-pp-app/main.py
